springdoc:
  packagesToScan:
    - com.assessment.hotelbooking.controller

server.port: 8808

spring:
  jpa:
    database: MYSQL
    openInView: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/configuration-optional.html
        jdbc:
          batch_size: 25
          batch_versioned_data: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        show_sql: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/hotel_booking_db?useUnicode=yes&characterEncoding=utf-8&useSSL=true&requireSSL=true"
    username: "${DB_USER:root}"
    password: "${DB_PWD:root}"
    hikari:
      connectionTimeout: 30000
      maxLifetime: 240000
      maximumPoolSize: 50
      minimumIdle: 5
      idleTimeout: 230000
      data-source-properties:
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        cache-prep-stmts: true
        use-server-prep-stmts: true
  aop:
    auto: false

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
      token-management-service:
        url: "${TOKEN_MANAGEMENT_SERVICE_URL:http://localhost:8809}"

hotel-regulations:
  code: "NW"
  check-in-time: "14:00"
  check-out-time: "12:00"
  minimum-age: 18